version: "2"
services:
  eval-service:
    build: eval-service
    command: python eval-service.py
    ports:
     - "5000:5000"
    volumes:
     - ./eval-service:/code
  defined-service:
    build: defined-service
    command: npm start
    ports:
     - "8080:8080"
    volumes: 
     - ./defined-service/:/app
  jaeger:
    image: jaegertracing/all-in-one:0.8.0
    ports:
     - "5775:5775"
     - "6381:6381"
     - "6382:6382"
     - "5778:5778"
     - "16686:16686"
     - "14268:14268"
     - "9411:9411"